---
- name: baitap
  hosts: all
  gather_facts: yes

  tasks:
    - name: dat ip cho loopback
      ios_l3_interface:
        name: loopback {{ item.number }}
        ipv4: 10.0.{{ item.number }}.1/24
      with_items:
        - { number: 1 }
        - { number: 2 }
        - { number: 3 }
 
    - name: Show ip
      ios_command:
        commands:
          - show ip int brief
      register: output

    - debug: var=output.stdout_lines
